data<-read.table("household_power_consumption.txt",header = T,sep = ";")
datadate<-as.Date(data$Date,"%d/%m/%Y")
data2<-subset(data,datadate>"2007-01-31"& datadate<"2007-02-03")
global_active_power<-as.numeric(as.character(data2$Global_active_power))
datetimetest<-paste(data2$Date, as.character(data2$Time))
datetime<-strptime(as.character(datetimetest), "%d/%m/%Y %H:%M:%S")
png(file="plot2.png",width=480,height=480)
plot(datetime,global_active_power,type="l",ylab="Global Active Power (kilowatts)", xlab="") 
dev.off()
