data<-read.table("household_power_consumption.txt",header = T,sep = ";")
datadate<-as.Date(data$Date,"%d/%m/%Y")
data2<-subset(data,datadate>"2007-01-31"& datadate<"2007-02-03")
global_active_power<-as.numeric(as.character(data2$Global_active_power))
submetering1<-as.numeric(as.character(data2$Sub_metering_1))
submetering2<-as.numeric(as.character(data2$Sub_metering_2))
submetering3<-as.numeric(as.character(data2$Sub_metering_3))
datetimetest<-paste(data2$Date, as.character(data2$Time))
datetime<-strptime(as.character(datetimetest), "%d/%m/%Y %H:%M:%S")
Voltage<-as.numeric(as.character(data2$Voltage))
Global_reactive_power<-as.numeric(as.character(data2$Global_reactive_power))
png(file="plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(datetime,global_active_power,type="l",ylab="Global Active Power (kilowatts)", xlab="")
plot(datetime,Voltage,type="l")
plot(datetime,submetering1,col="black",type="l",ylab="Energy sub metering", xlab="")
lines(datetime,submetering2,col="red")
lines(datetime,submetering3,col="blue")
legend("topright",lty = c(1,1,1),col=c("black","red","blue"),legend=c("sub_metering_1", "sub_metering_2","sub_metering_3"))
plot(datetime,Global_reactive_power,type = "l") 
dev.off()