setwd("~/Downloads/coursera/exploratory_ansalysis/")
data<-read.table("household_power_consumption.txt",header = T,sep = ";")
datadate<-as.Date(data$Date,"%d/%m/%Y")
data2<-subset(data,datadate>"2007-01-31"& datadate<"2007-02-03")
submetering1<-as.numeric(as.character(data2$Sub_metering_1))
submetering2<-as.numeric(as.character(data2$Sub_metering_2))
submetering3<-as.numeric(as.character(data2$Sub_metering_3))
datetimetest<-paste(data2$Date, as.character(data2$Time))
datetime<-strptime(as.character(datetimetest), "%d/%m/%Y %H:%M:%S")
png(file="test.png",width=480,height=480)
plot(datetime,submetering1,col="black",type="l",ylab="Energy sub metering", xlab="")
lines(datetime,submetering2,col="red")
lines(datetime,submetering3,col="blue")
legend("topright",lty = c(1,1,1),bty="n",col=c("black","red","blue"),legend=c("sub_metering_1", "sub_metering_2","sub_metering_3"))
dev.off()